// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // This file configures the Prisma CLI only — migrations. The running app never reads it;
    // it builds its own pool from DATABASE_URL in src/lib/prisma.ts. So this URL is
    // specifically the migration connection, and prefers a direct (non-pooled) one:
    // managed providers (Neon, Supabase) put PgBouncer in transaction mode behind their
    // pooled URL, which can't hold the session-level advisory locks and DDL transactions
    // Prisma Migrate relies on. Falls back to DATABASE_URL locally, where there's no pooler.
    // (Note: `directUrl` is not a valid key here in Prisma 7 — the split lives in the two
    // separate env vars instead.)
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
