// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
    // Migrations need a direct connection: managed Postgres providers (Neon, Supabase) hand
    // out a pooled URL for app queries, but that pooler runs in transaction mode, which can't
    // hold the session-level advisory locks and DDL transactions Prisma Migrate relies on.
    // Falls back to DATABASE_URL for local dev, where there's no pooler in front of the DB.
    directUrl: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
