import { prisma } from "@/lib/prisma";
import { getMap, getMapById, requestMapGeneration, type RustMapData } from "@/lib/external/rustmaps";

const MIN_SIZE = 1000;
const MAX_SIZE = 6000;

export type GetMapPreviewResult =
  | { ok: true; status: "ready"; map: RustMapData; fromCache: boolean }
  | { ok: true; status: "generating"; mapId: string; queuePosition: number | null }
  | { ok: false; error: string };

/**
 * Resolves a RustMaps preview for a given size+seed, caching the result indefinitely (map data
 * is immutable for a given size+seed). If the map hasn't been generated by RustMaps yet, this
 * kicks off generation and does a short poll — already-generated combos return near-instantly,
 * but a genuinely fresh combo can take well over a minute, so callers get a "generating" status
 * with the RustMaps mapId back instead of the request blocking indefinitely. Pass that mapId
 * back in as `knownMapId` on a follow-up call to resume polling without re-queuing generation.
 */
export async function getMapPreview(size: number, seed: number, knownMapId?: string): Promise<GetMapPreviewResult> {
  if (!Number.isInteger(size) || size < MIN_SIZE || size > MAX_SIZE) {
    return { ok: false, error: `Розмір мапи має бути цілим числом від ${MIN_SIZE} до ${MAX_SIZE}` };
  }
  if (!Number.isInteger(seed) || seed < 0) {
    return { ok: false, error: "Сід має бути цілим невід'ємним числом" };
  }

  const cacheKey = `${size}_${seed}`;
  const cached = await prisma.mapCache.findUnique({ where: { key: cacheKey } });
  if (cached) {
    return { ok: true, status: "ready", map: cached.data as unknown as RustMapData, fromCache: true };
  }

  if (knownMapId) {
    return resumePolling(cacheKey, knownMapId);
  }

  let map: RustMapData | null;
  try {
    map = await getMap(size, seed);
  } catch {
    return { ok: false, error: "Не вдалося звернутися до RustMaps" };
  }
  if (map) {
    await cacheMap(cacheKey, map);
    return { ok: true, status: "ready", map, fromCache: false };
  }

  let queued;
  try {
    queued = await requestMapGeneration(size, seed);
  } catch {
    return { ok: false, error: "Не вдалося запустити генерацію мапи" };
  }

  if (!queued) {
    // RustMaps reported success but returned no generation info — this happens when the map
    // already exists but the initial direct GET raced it; try once more before giving up.
    const retried = await getMap(size, seed);
    if (retried) {
      await cacheMap(cacheKey, retried);
      return { ok: true, status: "ready", map: retried, fromCache: false };
    }
    return { ok: false, error: "RustMaps не повернув дані мапи" };
  }

  return pollAFewTimes(cacheKey, queued.mapId, queued.queuePosition);
}

async function resumePolling(cacheKey: string, mapId: string): Promise<GetMapPreviewResult> {
  let polled: RustMapData | null;
  try {
    polled = await getMapById(mapId);
  } catch {
    return { ok: false, error: "Не вдалося перевірити стан генерації мапи" };
  }
  if (polled) {
    await cacheMap(cacheKey, polled);
    return { ok: true, status: "ready", map: polled, fromCache: false };
  }
  return { ok: true, status: "generating", mapId, queuePosition: null };
}

/** Two short polls (~5s total) — enough to catch fast generations without risking a long-running request. */
async function pollAFewTimes(
  cacheKey: string,
  mapId: string,
  queuePosition: number | null
): Promise<GetMapPreviewResult> {
  for (let attempt = 0; attempt < 2; attempt++) {
    await sleep(2500);
    let polled: RustMapData | null;
    try {
      polled = await getMapById(mapId);
    } catch {
      return { ok: false, error: "Не вдалося перевірити стан генерації мапи" };
    }
    if (polled) {
      await cacheMap(cacheKey, polled);
      return { ok: true, status: "ready", map: polled, fromCache: false };
    }
  }
  return { ok: true, status: "generating", mapId, queuePosition };
}

async function cacheMap(key: string, map: RustMapData) {
  const jsonData = JSON.parse(JSON.stringify(map));
  await prisma.mapCache.upsert({
    where: { key },
    create: { key, data: jsonData },
    update: { data: jsonData },
  });
}

function sleep(ms: number): Promise<void> {
  return new Promise((resolve) => setTimeout(resolve, ms));
}
